# Starter pipeline


trigger:
- main

pool:
  vmImage: ubuntu-latest
  # name: pilotrakc

steps:
- checkout: self
  fetchDepth: 0
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'wget "https://download.java.net/java/GA/jdk23.0.2/6da2a6609d6e406f85c491fcb119101b/7/GPL/openjdk-23.0.2_linux-x64_bin.tar.gz"'
    workingDirectory: '$(Build.SourcesDirectory)'
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '23'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: '$(Build.SourcesDirectory)/openjdk-23.0.2_linux-x64_bin.tar.gz'
    jdkDestinationDirectory: '$(Build.BinariesDirectory)/open-jdk'
    cleanDestinationDirectory: true

- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'SonarQube'
    organization: 'pilot1782'
    scannerMode: 'other'
    extraProperties: |
      sonar.projectKey=pilot1782_DEADGOAT
      sonar.projectName=DEADGOAT
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'verify clean install spotless:apply'
    options: '-X -e'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
# - task: Maven@4
#   inputs:
#     mavenPomFile: 'pom.xml'
#     goals: 'clean install spotless:apply'
#     options: '-X -e'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     javaHomeOption: 'JDKVersion'
#     mavenVersionOption: 'Default'
#     mavenAuthenticateFeed: false
#     effectivePomSkip: false
#     sonarQubeRunAnalysis: true
#     sqMavenPluginVersionChoice: 'latest'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"