# Starter pipeline


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'wget "https://download.java.net/java/GA/jdk23.0.2/6da2a6609d6e406f85c491fcb119101b/7/GPL/openjdk-23.0.2_linux-x64_bin.tar.gz"'
    workingDirectory: '$(Build.SourcesDirectory)'
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '23'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: '$(Build.SourcesDirectory)/openjdk-23.0.2_linux-x64_bin.tar.gz'
    jdkDestinationDirectory: '$(Build.SourcesDirectory)/open-jdk'
    cleanDestinationDirectory: true
- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'SonarQube'
    organization: 'carsonbountry'
    scannerMode: 'other'
    extraProperties: |
      sonar.projectKey=carsonbountry_DEADGOAT
      sonar.projectName=DEADGOAT
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install spotless:apply'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"